import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { ThemingProvider } from '../modules/theming/provider';
import { GraphQLProvider } from '../graphql/provider';

import "davinci/global.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GraphQLProvider>
        <ThemingProvider>
      <div className="container-wrapper">
        <div className="container py-6">
          {children}
          </div>
      </div>
      </ThemingProvider>
      </GraphQLProvider>
      </body>
    </html>
  );
}
